### ISSUE TITLE
IFrame Generator: wrong 'iframe' src link created when run locally

### ISSUE THREAD

**Issue by evgeniTUM** [ldbv-by/bav4#1973]
How to reproduce:
1. Share
2. Create IFrame Preview

Result: The generated code contains an invalid link:
`<iframe src=http://localhost:8081/embed.html/embed.html?...`

It seems that this happens only when run locally. If deployed the problem does not occur.

**Comment by taulinger** [comment]
Thx @evgeniTUM for the report
