### ISSUE TITLE
EWKT export: wrongt result for multiple geometries

### ISSUE THREAD

**Issue by evgeniTUM** [ldbv-by/bav4#1993]
It is possible to export a drawing to an EWKT file.
But when I try to import the same exported EWKT file the import fails with the message "the file type is not supported".

Issue:
When dragging the EWKT file (.txt) into the application the following D&D message is shown:
"KML/GPX/GeoJSON/EWKT Datei hierhin ziehen" which communicates to the user that an EWKT import is supported.

**Comment by taulinger** [comment]
@evgeniTUM Would you attach your EWKT file, please?

**Comment by evgeniTUM** [comment]
I just tested it again. If I export only one geometry (e.g. text) the file is being imported. But if I draw more than one geometry and export the whole drawing, then the file will not be imported.
 
Here is an example with two text elements:
[bayernatlas_20231009080259.txt](https://github.com/ldbv-by/bav4/files/12843764/bayernatlas_20231009080259.txt)

**Comment by taulinger** [comment]
There is a bug in the export functionality: More than one geometry must be encoded as Multi* or GeometryCollection type in (E)WKT.
I will adjust the title of this issue.
