### ISSUE TITLE
Routing and ElevationProfile have different data

### ISSUE THREAD

**Issue by alsturm** [ldbv-by/bav4#2189]
![numbers](https://github.com/ldbv-by/bav4/assets/76113751/c46c988f-491e-4ab2-8a03-d10c6ce0f65d)

**Comment by thiloSchlemmer** [comment]
The wording should also be harmonized:

![image](https://github.com/ldbv-by/bav4/assets/2117317/5f520c9f-5734-4d59-b2e9-827949c7a46f)

![image](https://github.com/ldbv-by/bav4/assets/2117317/7d04a5cf-864d-44c7-95e7-d9b259dd200c)
