### ISSUE TITLE
Routing: elevation profile closes after route points were changed

### ISSUE THREAD

**Issue by wiglgrimpft** [ldbv-by/bav4#2244]
Elevation profile adapts correctly after a new route alternative (e.g. fastest route) or routing variant (bicycle, hiking, mountain bike) is selected.
However, if you adjust the points (move existing points, add new intermediate points or delete intermediate points, change the order, etc.), the height profile closes. It can then be reopened.

**Comment by taulinger** [comment]
We need  #2369 to fix this issue...

**Comment by taulinger** [comment]
resolved by #2369
