### ISSUE TITLE
Chip-Content "Luftbildrecherchestation" empty

### ISSUE THREAD

**Issue by wiglgrimpft** [ldbv-by/bav4#2261]
The contents of the chip "Luftbildrecherchestation" are not loaded.

![Bildschirmfoto vom 2024-03-14 11-40-35](https://github.com/ldbv-by/bav4/assets/161747242/ac361088-6bef-4f89-b81d-33353a63d5bd)

**Comment by taulinger** [comment]
Thx, already fixed in the meantime
