### ISSUE TITLE
cloned drawing layer is not re-created

### ISSUE THREAD

**Issue by taulinger** [ldbv-by/bav4#2587]
After deactivating the drawing/measurement tool the original layer will not be re-created if it was cloned before.

**Comment by thiloSchlemmer** [comment]
reasons, why our approach is currently broken:

1.  OlDrawHandler/OlMeasurementHandler does not find the topmost layer -> must be inverted (or something else)
2.  OlDrawHandler/OlMeasurementHandler adds the new layer with layerId === fileId -> must be oldLayer.id or newUniqueId
3. LayerItem>cloneLayer() must result in a cloned GeoResource (new FileId)
