### ISSUE TITLE
Pdf export: Incorrect placement of grid labels when map is rotated

### ISSUE THREAD

**Issue by taulinger** [ldbv-by/bav4#2607]
![image](https://github.com/user-attachments/assets/b710c5d5-3dc4-47f3-8d59-8c6b1697ccca)

**Comment by thiloSchlemmer** [comment]
[MapFishPrint3 Bug](https://github.com/mapfish/mapfish-print/issues/2004) relates to this issue.

**Comment by thiloSchlemmer** [comment]
Resolved with #2619
