### ISSUE TITLE
FeatureInfo panel should be restoreable

### ISSUE THREAD

**Issue by taulinger** [ldbv-by/bav4#860]
After closing the main menu in **portrait mode**. the FeatureInfo panel can not be opened again
1) close the main menu containing the FeatureInfo
![grafik](https://user-images.githubusercontent.com/49945713/161269931-120a6fd3-a79b-4f4b-b865-f46b3087f1e9.png)
2) no chance to re-open it
![grafik](https://user-images.githubusercontent.com/49945713/161270104-63dc258d-3b6c-4252-b429-966f4df65444.png)

**Comment by alsturm** [comment]
Suggestions:

- Marker and Objekt-Info point shut be clickable and open panel with info...

niice to have:

-  Same size of the points.
-  Give posiotn also a point.
-  Give marker a  white border .


![Screenshot](https://user-images.githubusercontent.com/76113751/164234409-a13f7ee2-6d99-4188-9c02-8df9b47378d3.png)

![Screenshot1](https://user-images.githubusercontent.com/76113751/164235555-6b0264bd-40af-4e19-beed-3af0374c4ebd.png)
